# apps.yaml - Blueprint for Apps Collection
title: App
sections:
  main:
    display: Main Content
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          display: App Name
      -
        handle: slug
        field:
          type: slug
          required: true
          validate:
            - required
          display: URL Slug
          generate_from: title
      -
        handle: app_description
        field:
          type: markdown
          display: App Description
          instructions: Full description with supported markdown formatting
      -
        handle: short_description
        field:
          type: textarea
          display: Short Description
          character_limit: 120
          instructions: Brief description for featured cards and listings
      -
        handle: icon
        field:
          type: assets
          container: app_assets
          max_files: 1
          display: App Icon
          instructions: Square app icon (512x512px recommended)
      -
        handle: screenshots
        field:
          type: assets
          container: app_assets
          max_files: 5
          display: Screenshots
          instructions: App screenshots for gallery view
      -
        handle: featured_image
        field:
          type: assets
          container: app_assets
          max_files: 1
          display: Featured Image
          instructions: Wide banner image for featured section (1200x600px recommended)
  sidebar:
    display: App Details
    fields:
      -
        handle: size
        field:
          type: text
          display: App Size
          instructions: Size in MB (e.g., 45MB)
      -
        handle: rating
        field:
          type: float
          display: Rating
          instructions: Rating from 1.0 to 5.0
          validate:
            - min:1
            - max:5
      -
        handle: version
        field:
          type: text
          display: Version
          instructions: Current app version (e.g., 2.1.4)
      -
        handle: developer
        field:
          type: text
          display: Developer Name
      -
        handle: category
        field:
          type: select
          options:
            productivity: Productivity
            photo_video: Photo & Video
            social: Social Media
            utilities: Utilities
            education: Education
            finance: Finance
            health: Health & Fitness
          display: Category
          default: productivity
      -
        handle: featured
        field:
          type: toggle
          display: Featured App
          instructions: Show in featured section
          default: false
      -
        handle: is_trending
        field:
          type: toggle
          display: Trending
          instructions: Show in trending section
          default: false
  monetization:
    display: CPA & Monetization
    fields:
      -
        handle: content_locker
        field:
          type: toggle
          display: Enable Content Locker
          instructions: Lock app download behind CPA offer
          default: false
      -
        handle: cpa_type
        field:
          type: select
          options:
            none: None
            email: Email Submit
            survey: Survey Completion
            app_install: App Install
            sign_up: Account Creation
          display: CPA Offer Type
          default: none
          if:
            content_locker: true
      -
        handle: cpa_link
        field:
          type: text
          display: CPA Offer Link
          instructions: Link to CPA offer page
          if:
            content_locker: true
      -
        handle: smart_link_enabled
        field:
          type: toggle
          display: Enable Smart Link
          instructions: Use smart links for platform detection
          default: false
      -
        handle: android_link
        field:
          type: text
          display: Android Download Link
          instructions: Link to Google Play or custom Android page
          if:
            smart_link_enabled: true
      -
        handle: ios_link
        field:
          type: text
          display: iOS Download Link
          instructions: Link to App Store or custom iOS page
          if:
            smart_link_enabled: true
      -
        handle: default_link
        field:
          type: text
          display: Default Download Link
          instructions: Fallback link for direct download or other platforms
      -
        handle: processing_time
        field:
          type: integer
          display: Processing Time (ms)
          instructions: Time in milliseconds for the download processing animation
          default: 2000

